### ISSUE TITLE
module 'byteps.torch' has no attribute 'send_async' / recv_async

### ISSUE THREAD

**Issue by sljlp** [volcengine/veGiantModel#4]
hi，按照你们的readme跑了一下代码，
![image](https://user-images.githubusercontent.com/30228238/160785302-0bf8947c-f007-4500-b8c8-8040740fa0d3.png)
出现这个问题
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/30228238/160783672-24c89937-2562-490c-9bbe-ee874bed5ab5.png">
我以为是byteps版本不对，因此找了所有commit的改动
我找了master分支所有版本的byteps源码的改动，发现没有send_async/recv_async 方法
请问是哪里出了问题呢?

**Comment by itszyin** [comment]
You can follow the [step-by-step-tutorial.md](https://github.com/volcengine/veGiantModel/blob/main/docs/step-by-step-tutorial.md) to do more exploration.

In this file, you can see:
```bash
git clone --recursive -b bccl-github https://github.com/bytedance/byteps.git
cd byteps
python3 setup.py install
```

The branch [bccl-github](https://github.com/bytedance/byteps/blob/b8c0b76c1c088c629786727b07d1c0be156bb604/byteps/torch/ops.py#L177) has  `send_async` and `recv_async` functions.

**Comment by sljlp** [comment]
好的，多谢
